(* This is a helper program used to generate dune rules that get included to the
   parent directory's dune file, via [../dune.inc]. *)

let () =
  Printf.printf
    "; dune file generated by './gen-dune/main.exe' -- do not edit.\n";
  Sys.argv |> Array.to_list |> List.tl |> List.sort String.compare
  |> List.iter (fun arg ->
         List.iter
           (fun ext ->
             let file = arg ^ ext in
             Printf.printf
               {|
(rule
 (alias runtest)
 (action
  (diff %s.expected %s)))
|}
               file file)
           [ ".ml"; ".mli" ])
