// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocamloptions.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ocamloptions.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* OCamlType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* OCamlContainer_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ocamloptions_2eproto() {
  protobuf_AddDesc_ocamloptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ocamloptions.proto");
  GOOGLE_CHECK(file != NULL);
  OCamlType_descriptor_ = file->enum_type(0);
  OCamlContainer_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ocamloptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_ocamloptions_2eproto() {
}

void protobuf_AddDesc_ocamloptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022ocamloptions.proto\032 google/protobuf/de"
    "scriptor.proto*\026\n\tOCamlType\022\t\n\005int_t\020\001*$"
    "\n\016OCamlContainer\022\022\n\016repeated_field\020\001:\?\n\n"
    "ocaml_type\022\035.google.protobuf.FieldOption"
    "s\030\242\215\006 \001(\0162\n.OCamlType:I\n\017ocaml_container"
    "\022\035.google.protobuf.FieldOptions\030\243\215\006 \001(\0162"
    "\017.OCamlContainer:6\n\rocaml_mutable\022\035.goog"
    "le.protobuf.FieldOptions\030\244\215\006 \001(\010:>\n\nint3"
    "2_type\022\034.google.protobuf.FileOptions\030\242\215\006"
    " \001(\0162\n.OCamlType:>\n\nint64_type\022\034.google."
    "protobuf.FileOptions\030\243\215\006 \001(\0162\n.OCamlType", 440);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ocamloptions.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    100002, 14, false, false,
    &::OCamlType_IsValid);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    100003, 14, false, false,
    &::OCamlContainer_IsValid);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    100004, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::google::protobuf::FileOptions::default_instance(),
    100002, 14, false, false,
    &::OCamlType_IsValid);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::google::protobuf::FileOptions::default_instance(),
    100003, 14, false, false,
    &::OCamlType_IsValid);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ocamloptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ocamloptions_2eproto {
  StaticDescriptorInitializer_ocamloptions_2eproto() {
    protobuf_AddDesc_ocamloptions_2eproto();
  }
} static_descriptor_initializer_ocamloptions_2eproto_;
const ::google::protobuf::EnumDescriptor* OCamlType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OCamlType_descriptor_;
}
bool OCamlType_IsValid(int value) {
  switch(value) {
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* OCamlContainer_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OCamlContainer_descriptor_;
}
bool OCamlContainer_IsValid(int value) {
  switch(value) {
    case 1:
      return true;
    default:
      return false;
  }
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlType, ::OCamlType_IsValid>, 14, false >
  ocaml_type(kOcamlTypeFieldNumber, static_cast< ::OCamlType >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlContainer, ::OCamlContainer_IsValid>, 14, false >
  ocaml_container(kOcamlContainerFieldNumber, static_cast< ::OCamlContainer >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  ocaml_mutable(kOcamlMutableFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlType, ::OCamlType_IsValid>, 14, false >
  int32_type(kInt32TypeFieldNumber, static_cast< ::OCamlType >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlType, ::OCamlType_IsValid>, 14, false >
  int64_type(kInt64TypeFieldNumber, static_cast< ::OCamlType >(1));

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
