// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocamloptions.proto

#ifndef PROTOBUF_ocamloptions_2eproto__INCLUDED
#define PROTOBUF_ocamloptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ocamloptions_2eproto();
void protobuf_AssignDesc_ocamloptions_2eproto();
void protobuf_ShutdownFile_ocamloptions_2eproto();


enum OCamlType {
  int_t = 1
};
bool OCamlType_IsValid(int value);
const OCamlType OCamlType_MIN = int_t;
const OCamlType OCamlType_MAX = int_t;
const int OCamlType_ARRAYSIZE = OCamlType_MAX + 1;

const ::google::protobuf::EnumDescriptor* OCamlType_descriptor();
inline const ::std::string& OCamlType_Name(OCamlType value) {
  return ::google::protobuf::internal::NameOfEnum(
    OCamlType_descriptor(), value);
}
inline bool OCamlType_Parse(
    const ::std::string& name, OCamlType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OCamlType>(
    OCamlType_descriptor(), name, value);
}
enum OCamlContainer {
  repeated_field = 1
};
bool OCamlContainer_IsValid(int value);
const OCamlContainer OCamlContainer_MIN = repeated_field;
const OCamlContainer OCamlContainer_MAX = repeated_field;
const int OCamlContainer_ARRAYSIZE = OCamlContainer_MAX + 1;

const ::google::protobuf::EnumDescriptor* OCamlContainer_descriptor();
inline const ::std::string& OCamlContainer_Name(OCamlContainer value) {
  return ::google::protobuf::internal::NameOfEnum(
    OCamlContainer_descriptor(), value);
}
inline bool OCamlContainer_Parse(
    const ::std::string& name, OCamlContainer* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OCamlContainer>(
    OCamlContainer_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kOcamlTypeFieldNumber = 100002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlType, ::OCamlType_IsValid>, 14, false >
  ocaml_type;
static const int kOcamlContainerFieldNumber = 100003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlContainer, ::OCamlContainer_IsValid>, 14, false >
  ocaml_container;
static const int kOcamlMutableFieldNumber = 100004;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  ocaml_mutable;
static const int kInt32TypeFieldNumber = 100002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlType, ::OCamlType_IsValid>, 14, false >
  int32_type;
static const int kInt64TypeFieldNumber = 100003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::OCamlType, ::OCamlType_IsValid>, 14, false >
  int64_type;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::OCamlType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OCamlType>() {
  return ::OCamlType_descriptor();
}
template <> struct is_proto_enum< ::OCamlContainer> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OCamlContainer>() {
  return ::OCamlContainer_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ocamloptions_2eproto__INCLUDED
